Fix build error
[Model] All
[BinType] AP
[Customer] OPEN

[Issue#] N/A
[Request] N/A
[Occurrence Version] N/A

[Problem] build error at pool.hpp
    ./boost/pool/pool.hpp:361:28: error: 'math' has not been declared

[Cause & Measure] Invalid merge at "Bump to 1.58.0"
[Checking Method] build test

[Team] Open Source Management and Setting Part
[Developer] dh0128.kwak
[Solution company] Samsung
[Change Type] N/A

Change-Id: I626490e3ea85450441b704bef3d646813f053ad0
Signed-off-by: DongHun Kwak <dh0128.kwak@samsung.com>